### ISSUE TITLE
Getting GMSThreadException when adding and removing map with annotation/polylines multiple times

### ISSUE THREAD

**Issue by alperdincer** [alperdincer/TiGMap#1]
There is a problem with module that when you add/remove map with annotations or polylines multiple times (after 2 additions) you will get the following error : 

[ERROR] The application has crashed with an uncaught exception 'GMSThreadException'.
[DEBUG] Reason:
[DEBUG] All calls to the Google Maps SDK for iOS must be made from the UI thread
[DEBUG] Stack trace:
[DEBUG] 0   CoreFoundation                      0x0426f012 **exceptionPreprocess + 178
[DEBUG] 1   libobjc.A.dylib                     0x01c95e7e objc_exception_throw + 44
[DEBUG] 2   CoreFoundation                      0x0426edeb +[NSException raise:format:] + 139
[DEBUG] 3   MekansalGMap                        0x0041192d -[GMSOverlay setMap:] + 101
[DEBUG] 4   MekansalGMap                        0x00567f3f -[ComMekansalGmapiosAnnotationProxy dealloc] + 57
[DEBUG] 5   libobjc.A.dylib                     0x01ca99ff -[NSObject release] + 47
[DEBUG] 6   MekansalGMap                        0x00058d1f -[KrollObject dealloc] + 159
[DEBUG] 7   libobjc.A.dylib                     0x01ca99ff -[NSObject release] + 47
[DEBUG] 8   MekansalGMap                        0x000572d4 KrollFinalizer + 532
[DEBUG] 9   MekansalGMap                        0x0041e5e3 _ZN2TI20TiCallbackObjectData8finalizeENS_6HandleINS_7UnknownEEEPv + 51
[DEBUG] 10  MekansalGMap                        0x0046083b _ZN2TI10HandleHeap19finalizeWeakHandlesEv + 155
[DEBUG] 11  MekansalGMap                        0x004619ed _ZN2TI4Heap17collectAllGarbageEv + 45
[DEBUG] 12  MekansalGMap                        0x0041d142 TiGarbageCollect + 66
[DEBUG] 13  MekansalGMap                        0x0004fddb -[KrollContext forceGarbageCollectNow] + 123
[DEBUG] 14  MekansalGMap                        0x000511b0 -[KrollContext main] + 4976
[DEBUG] 15  Foundation                          0x021dd805 -[NSThread main] + 76
[DEBUG] 16  Foundation                          0x021dd764 __NSThread__main** + 1304
[DEBUG] 17  libsystem_c.dylib                   0x97a065b7 _pthread_start + 344
[DEBUG] 18  libsystem_c.dylib                   0x979f0d4e thread_start + 34
[DEBUG] 2013-06-12 14:22:38.861 MekansalGMap[11607:3a03] **\* Terminating app due to uncaught exception 'GMSThreadException', reason: 'All calls to the Google Maps SDK for iOS must be made from the UI thread'
[DEBUG] **\* First throw call stack:
[DEBUG](0x426f012 0x1c95e7e 0x426edeb 0x41192d 0x567f3f 0x1ca99ff 0x58d1f 0x1ca99ff 0x572d4 0x41e5e3 0x46083b 0x4619ed 0x41d142 0x4fddb 0x511b0 0x21dd805 0x21dd764 0x97a065b7 0x979f0d4e)

I think there is a leak in the code, but I can't find the problem. 

You can run the sample code and click "Open Map" button and go back. Then click "Open Map" and go back. Then the code will give the error given above.

**Comment by alperdincer** [comment]
It's already solved. I just forgot to close the issue.

**Comment by AnnieNinaJoyceV** [comment]
@alperdincer Hi! I'm facing the same issue. Could you please share the solution?

-Thanks

**Comment by shivaramt** [comment]
How did you fix the issue ? Please provide the solution.

**Comment by elvinaze** [comment]
The location property must be set with a CLLocationCoordinate2D

To make a new locationcoordinate use this:

 CLLocationCoordinate2D(latitude: CLLocationDegrees(<latitude>), longitude: CLLocationDegrees(<longitude>))
It's really simple.. Make sure your map is initialized by doing that

**Comment by elvinaze** [comment]
```
dispatch_async(dispatch_get_main_queue(),
{
    "Your Previous code here" 
})
```

**Comment by Lyankar** [comment]
In my case it's demanding to use main thread in two places

One is...

    __block GMSMapView *mapView;
    dispatch_async(dispatch_get_main_queue(), ^{
        // Create GMSMapView
        mapView = [GMSMapView mapWithFrame:CGRectMake(1, 1, _subView.frame.size.width-2, _subView.frame.size.height-2) camera:camera];
        mapView.myLocationEnabled = YES;
       [_subView addSubview:mapView];
    });

Second one is...

    - (void)fetchPolylineWithOrigin:(CLLocation *)origin destination:(CLLocation *)destination completionHandler:(void (^)(GMSPolyline *))completionHandler {

      // Code here ....

       __block GMSPolyline *polyline = nil;
       dispatch_async(dispatch_get_main_queue(), ^{ // Second main
            if ([routesArray count] > 0) {
                NSDictionary *routeDict = [routesArray objectAtIndex:0];
                NSDictionary *routeOverviewPolyline = [routeDict objectForKey:@"overview_polyline"];
                NSString *points = [routeOverviewPolyline objectForKey:@"points"];
                GMSPath *path = [GMSPath pathFromEncodedPath:points];
                polyline = [GMSPolyline polylineWithPath:path];
            }
        });
    }
