### ISSUE TITLE
Compiled module

### ISSUE THREAD

**Issue by mutationevent** [alperdincer/TiGMap#2]
Hi, Can you provide a compiled module for Ti SDK 3.1 ?
I am having trouble compiling it on my machine
Thanks a lot.

**Comment by alperdincer** [comment]
What error you are getting?

**Comment by alperdincer** [comment]
You can also download the compiled module from https://github.com/alperdincer/TiGMap/releases/1.0

Make sure that you have the Google Maps iOS SDK and change the module.xcconfig file according to your paths.
