### ISSUE TITLE
Cant setlocation nor set an custom image for the marker

### ISSUE THREAD

**Issue by caiocost** [alperdincer/TiGMap#4]
Hi, thanks for sharing your project, ive successfully manage to make it run, but when I change the property "image" from Map.createAnnotation it shows the generic one on the map, and i cant find a way to pan the map to another center with setRegion or setLocation, not even setting location:{latitude: x, longitude: y} on the Map.CreateView()

Thanks in advance!

**Comment by caiocost** [comment]
and Im using the 1.7.2 version of the SDK...

**Comment by HIDEKIT** [comment]
I had the same problem.
My solution is using 1.6.2 version of the SDK.
https://developers.google.com/maps/documentation/ios/releases

Please try it.

**Comment by alperdincer** [comment]
Hi,

You can add the following code block to ComMekansalGmapiosView.m

-(void)zoomToBBOX:(NSArray*)args
{
    ENSURE_UI_THREAD(zoomToBBOX, args);
    //arg0 -> centerLat, arg1 -> centerLng, arg2 -> deltaLat, arg3 -> deltaLng
    float centerLat = [[args objectAtIndex: 0] floatValue];
    float centerLng = [[args objectAtIndex: 1] floatValue];
    float deltaLat = [[args objectAtIndex: 2] floatValue];
    float deltaLng = [[args objectAtIndex: 3] floatValue];

```
float northEastLat = centerLat + (deltaLat / 2);
float northEastLng = centerLng + (deltaLng / 2);
float southWestLat = centerLat - (deltaLat / 2);
float southWestLng = centerLng - (deltaLng / 2);

CLLocationCoordinate2D northEast = CLLocationCoordinate2DMake(northEastLat, northEastLng);
CLLocationCoordinate2D southWest = CLLocationCoordinate2DMake(southWestLat, southWestLng);

GMSCoordinateBounds *zoomBounds = [[GMSCoordinateBounds alloc] initWithCoordinate:northEast coordinate:southWest];

GMSCameraUpdate *camUpdate = [GMSCameraUpdate fitBounds:zoomBounds];
[[self map] moveCamera:camUpdate];    
```

}

And use it like
map.zoomToBBOX(lat, lng, deltaLat, deltaLng);

Hope this will solve your problem.

Alper.
